### ISSUE TITLE
Copy (Kokkos) implementation for `apply` in `Tpetra::BlockCrsMatrix` into Kokkos-Kernels

### ISSUE THREAD

**Issue by fnrizzi** [fnrizzi/kokkos-kernels#4]
Assignee: @uhetmaniuk
PR:

**Comment by uhetmaniuk** [comment]
Will close this issue because `Tpetra::BlockCrsMatrix` and KokkosSparse::Experimental::BlockCrsMatrix` do not have the same storage of numerical values.
